#!/usr/bin/perl
#
#########################################################################
#
# Copyright © 2007,2008,2009,2010 Stefan Kangas <stefan@marxist.se>
#
#########################################################################
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
#########################################################################

use strict;
use warnings;

use Getopt::Long;
use String::MkPasswd qw(mkpasswd);

my $length;
my $minnum;
my $minspecial;
my $minupper;
    
GetOptions(
    'length=i' => \$length,
    'minnum=i' => \$minnum,
    'minspecial=i' => \$minspecial,
    'minupper=i' => \$minupper,
) or die "Unable to get command line options.";

$length     //= 10;
$minnum     //= int( rand ( $length / 3 ) ) || 1;
$minupper   //= int( rand ( $length / 3 ) ) || 1;
$minspecial //= int( rand ( $length / 3 ) ) || 1;

# do it
print mkpasswd(
    -length     => $length,
    -minnum     => 2,
    -minlower   => 1,           # minlower is increased if necessary
    -minupper   => $minupper,
    -minspecial => $minspecial,
    -distribute => 1,
);
print "\n";

