#!/bin/bash

# Shell wrapper for ncmpcpp that starts mpd if it is not already running.

options="$@"

if [ "`ps -A | grep -m1 mpd | awk '{print $1}'`" == "" ] && [ "$options" == "" ]; then
   mpd
fi

if [ -e /usr/bin/ncmpcpp ]; then
    /usr/bin/ncmpcpp $options
elif [ -e /usr/local/bin/ncmpcpp ]; then
    /usr/local/bin/ncmpcpp $options
else
    echo "ncmpcpp: command not found"
fi
